server:
  port: 8081
  servlet:
    context-path: /clipped

spring:
  application:
    name: clipped
  datasource:
    url: jdbc:mysql://localhost:3306/clipped
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"
