server:
  port: 8080
  servlet:
    context-path: /clipped

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clipped
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
